### ISSUE TITLE
RPC Haven

### ISSUE THREAD

**Issue by NumberOneGod** [lucasluqui/SK-DiscordRPC#1]
While in Haven, it doesn't display that I'm in, well, Haven.
This was tested on Steam version of the game, both windowed and fullscreen, as well as Steam account, and Standalone Account using Steam app.
This was also tested in other miscelanious places like OCH and FSC, but still only displayed my time in the game like the image above shows:
![bug](https://user-images.githubusercontent.com/58693960/70440234-a2a84580-1a89-11ea-9f79-80860232d39e.PNG)
The app was launched on Admin privileges 
![bug2](https://user-images.githubusercontent.com/58693960/70440401-06327300-1a8a-11ea-9e78-777dbf02d7df.PNG)

**Comment by lucasluqui** [comment]
All of the files must be placed inside the game's main directory, along with its files. From what I can see on the last screenshot you've created a new folder for them, which leads to the application not working correctly.
